##
## EPITECH PROJECT, 2024
## makefile
## File description:
## compiling with 102architect
##

SRC = architect.c	\

NAME = 102architect

all:
	gcc -o 102architect $(SRC) -lm
clean:
	rm -f *~

fclean: clean
	rm -f *#

re: fclean all
