##
## EPITECH PROJECT, 2024
## makefile
## File description:
## compiling with 104neutrinos
##

SRC	=	*.c

all:
	gcc -o 105demography $(SRC) -lm -g3

clean:
	rm -f *~
	rm -f *#

fclean: clean
	rm 105demography

re: fclean all
