##
## EPITECH PROJECT, 2024
## makefile
## File description:
## compiling with 103cipher
##

SRC = cipher.c	\

NAME = 103cipher

all:
	gcc -o 103cipher $(SRC) -lm
clean:
	rm -f *~

fclean: clean
	rm -f *#
	rm 103cipher

re: fclean all
