##
## EPITECH PROJECT, 2024
## makefile
## File description:
## compiling with 104neutrinos
##

SRC	=	src/*.c

all:
	gcc -o 106bombyx $(SRC) -lm -g3

clean:
	rm -f *~
	rm -f *#

fclean: clean
	rm 106bombyx

re: fclean all
