##
## EPITECH PROJECT, 2024
## makefile
## File description:
## compiling with 104neutrinos
##

SRC	=	*.c

all:
	gcc -o tail $(SRC) -g3

clean:
	rm -f *~
	rm -f *#

fclean: clean
	rm tail

re: fclean all
