##
## EPITECH PROJECT, 2024
## makefile
## File description:
## compiling with 104neutrinos
##

SRC	=	pong.c	\

all:
	gcc -o 101pong $(SRC) -lm -g3

clean:
	rm -f *~

fclean: clean
	rm -f *#
	rm 101pong

re: fclean all
