##
## EPITECH PROJECT, 2024
## Makefile
## File description:
## Compiling my my_ls
##

SRC = my_ls.c	\
	my_putchar.c	\
	my_putstr.c	\

NAME = my_ls

all:
	gcc -o my_ls $(SRC)
clean:
	rm -f *~

fclean: clean
	rm -f *#

re: fclean all
