##
## EPITECH PROJECT, 2024
## makefile
## File description:
## compiling with organised
##

SRC = *.c

NAME = organized

all:
	gcc -o organized $(SRC) -lm libshell.a -g3
clean:
	rm -f *~

fclean: clean
	rm -f *#
	rm organized

re: fclean all
